# $Id: Makefile.dist,v 1.4.12.1 2002/06/06 21:07:55 jsmith2 Exp $

COMPILE_ET = /usr/local/bin/compile_et
SNMPGEN = ../snmp/snmpgen

BUILT_SOURCES = imap_err.h imap_err.c \
	lmtpstats.c lmtpstats.h \
	pushstats.c pushstats.h

dist: $(BUILT_SOURCES)

imap_err.h imap_err.c: imap_err.et
	$(COMPILE_ET) imap_err.et

pushstats.c pushstats.h: pushstats.snmp
	$(SNMPGEN) pushstats.snmp

lmtpstats.c lmtpstats.h: lmtpstats.snmp
	$(SNMPGEN) lmtpstats.snmp
