/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "Pusher.pb-c.h"
void   channel_ready__init
                     (ChannelReady         *message)
{
  static ChannelReady init_value = CHANNEL_READY__INIT;
  *message = init_value;
}
size_t channel_ready__get_packed_size
                     (const ChannelReady *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &channel_ready__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t channel_ready__pack
                     (const ChannelReady *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &channel_ready__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t channel_ready__pack_to_buffer
                     (const ChannelReady *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &channel_ready__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChannelReady *
       channel_ready__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChannelReady *)
     protobuf_c_message_unpack (&channel_ready__descriptor,
                                allocator, len, data);
}
void   channel_ready__free_unpacked
                     (ChannelReady *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &channel_ready__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mod_seq_update__init
                     (ModSeqUpdate         *message)
{
  static ModSeqUpdate init_value = MOD_SEQ_UPDATE__INIT;
  *message = init_value;
}
size_t mod_seq_update__get_packed_size
                     (const ModSeqUpdate *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mod_seq_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mod_seq_update__pack
                     (const ModSeqUpdate *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mod_seq_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mod_seq_update__pack_to_buffer
                     (const ModSeqUpdate *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mod_seq_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModSeqUpdate *
       mod_seq_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModSeqUpdate *)
     protobuf_c_message_unpack (&mod_seq_update__descriptor,
                                allocator, len, data);
}
void   mod_seq_update__free_unpacked
                     (ModSeqUpdate *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mod_seq_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor channel_ready__field_descriptors[3] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChannelReady, user),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "session",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChannelReady, session),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ChannelReady, channel),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned channel_ready__field_indices_by_name[] = {
  2,   /* field[2] = channel */
  1,   /* field[1] = session */
  0,   /* field[0] = user */
};
static const ProtobufCIntRange channel_ready__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor channel_ready__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ChannelReady",
  "ChannelReady",
  "ChannelReady",
  "",
  sizeof(ChannelReady),
  3,
  channel_ready__field_descriptors,
  channel_ready__field_indices_by_name,
  1,  channel_ready__number_ranges,
  (ProtobufCMessageInit) channel_ready__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mod_seq_update__field_descriptors[5] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ModSeqUpdate, user),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "folders",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(ModSeqUpdate, n_folders),
    PROTOBUF_C_OFFSETOF(ModSeqUpdate, folders),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "modseq",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ModSeqUpdate, modseq),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "uidnext",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ModSeqUpdate, uidnext),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "uidvalidity",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ModSeqUpdate, uidvalidity),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned mod_seq_update__field_indices_by_name[] = {
  1,   /* field[1] = folders */
  2,   /* field[2] = modseq */
  3,   /* field[3] = uidnext */
  4,   /* field[4] = uidvalidity */
  0,   /* field[0] = user */
};
static const ProtobufCIntRange mod_seq_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mod_seq_update__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ModSeqUpdate",
  "ModSeqUpdate",
  "ModSeqUpdate",
  "",
  sizeof(ModSeqUpdate),
  5,
  mod_seq_update__field_descriptors,
  mod_seq_update__field_indices_by_name,
  1,  mod_seq_update__number_ranges,
  (ProtobufCMessageInit) mod_seq_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
